---

name: Setup time calculation dependencies in Docker
description: Builds and caches a Docker container of all dependencies
inputs:
  GITHUB_TOKEN:
    description: A GitHub access token
    required: true

runs:
  using: composite
  steps:
    # Expects actions/checkout to have already run
    - name: Mask secrets in logs
      shell: bash
      run: |
        echo "::add-mask::${{ inputs.GITHUB_TOKEN }}"

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        file: ./data/Dockerfile
        context: .
        tags: opentimes:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        provenance: false
        outputs: type=docker,dest=/tmp/opentimes.tar

    - name: Upload image artifact
      uses: actions/upload-artifact@v4
      with:
        name: opentimes-docker-${{ hashFiles('./data/Dockerfile', './pyproject.toml') }}
        path: /tmp/opentimes.tar
        retention-days: 3
        overwrite: true
