---

name: Fetch Valhalla tile tarballs
description: Fetch compressed tarballs of Valhalla tiles
inputs:
  year:
    description: Census year of the tile data to fetch
    required: true
  state:
    description: Census state code of the tile data to fetch
    required: true

runs:
  using: composite
  steps:
    # Assumes actions/checkout and setup-cloudflare-s3 have already been run
    - name: Cache restore tile input data
      id: cache-restore-tile-input
      uses: actions/cache/restore@v4
      with:
        path: ./data/intermediate/valhalla_tiles
        key: valhalla-tiles-${{ inputs.year }}-${{ inputs.state }}-${{ hashFiles('./data/dvc.lock') }}

    - name: Install DVC
      if: steps.cache-restore-tile-input.outputs.cache-hit != 'true'
      uses: ./.github/actions/setup-dvc

    - name: Pull DVC objects
      if: steps.cache-restore-tile-input.outputs.cache-hit != 'true'
      shell: bash
      working-directory: 'data'
      run: |
        tile_path=year=${{ inputs.year }}/geography=state/state=${{ inputs.state }}
        uv run dvc pull --no-run-cache \
          ./intermediate/valhalla_tiles/"$tile_path"/valhalla_tiles.tar.zst

    - name: Cache save tile input data
      if: steps.cache-restore-tile-input.outputs.cache-hit != 'true'
      id: cache-save-tile-input
      uses: actions/cache/save@v4
      with:
        path: ./data/intermediate/valhalla_tiles
        key: valhalla-tiles-${{ inputs.year }}-${{ inputs.state }}-${{ hashFiles('./data/dvc.lock') }}
