---

name: Fetch custom R5 JAR
description: Fetch/cache custom R5 JAR file
inputs:
  CLOUDFLARE_ACCOUNT_ID:
    description: A Cloudflare account ID string
    required: true

runs:
  using: composite
  steps:
    # Assumes actions/checkout and setup-cloudflare-s3 have already been run
    - name: Cache restore custom JAR
      id: cache-restore-custom-jar
      uses: actions/cache/restore@v4
      with:
        path: ./data/jars
        key: jar-${{ hashFiles('./data/jars/r5-custom.jar.md5') }}

    - name: Fetch custom R5 jar
      if: ${{ steps.cache-restore-custom-jar.outputs.cache-hit != 'true' }}
      shell: bash
      working-directory: 'data'
      run: |
        aws s3 cp --quiet --endpoint-url \
          https://${{ inputs.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com \
          s3://opentimes-resources/jars/r5-custom.jar ./jars/r5-custom.jar \
          --profile cloudflare

    - name: Cache save custom JAR
      if: ${{ steps.cache-restore-custom-jar.outputs.cache-hit != 'true' }}
      id: cache-save-custom-jar
      uses: actions/cache/save@v4
      with:
        path: ./data/jars
        key: jar-${{ hashFiles('./data/jars/r5-custom.jar.md5') }}
