---

services:
  # https://github.com/nilsnolde/docker-valhalla/blob/master/docker-compose.yml
  valhalla-build:
    image: ghcr.io/gis-ops/docker-valhalla/valhalla:latest
    container_name: valhalla-build
    user: 59999:59999
    build:
      context: .
      dockerfile: data/Dockerfile
    volumes:
      - ./data/build/:/custom_files
    environment:
      - serve_tiles=False
      - tileset_name=tiles
      - build_elevation=True
      - build_admins=True
      - build_time_zones=True
      - build_transit=False
      - build_tar=True
      - force_rebuild=True
      - update_existing_config=True
      - use_default_speeds_config=True
      - traffic_name=

  valhalla-run:
    image: ghcr.io/gis-ops/docker-valhalla/valhalla:latest
    container_name: valhalla-build
    user: 59999:59999
    build:
      context: .
      dockerfile: data/Dockerfile
    ports:
      - 8002:8002
    volumes:
      - ./data/build/:/custom_files
    environment:
      - use_tiles_ignore_pbf=True
      - update_existing_config=False
      - force_rebuild=False
      - tileset_name=tiles
