---

services:
  opentimes:
    image: ghcr.io/dfsnow/opentimes:latest
    container_name: opentimes
    hostname: opentimes
    build:
      context: .
      dockerfile: data/Dockerfile
    restart: never
    environment:
      - R_USER_CACHE_DIR
    volumes:
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
      - ./data/src:/times/src:ro
      - ./data/input:/times/input:rw
      - ./data/intermediate:/times/intermediate:rw
      - ./data/output:/times/output:rw
      - ./data/jars:/times/jars:ro
      - ./data/params.yaml:/times/params.yaml:ro
      # So git2r in Docker can read git info and add it to output metadata
      - ./.git:/times/.git:ro
