---

services:
  # https://github.com/nilsnolde/docker-valhalla/blob/master/docker-compose.yml
  valhalla-build:
    image: opentimes:latest
    container_name: valhalla-build
    user: ${USER_ID}:${GROUP_ID}
    build:
      context: .
      dockerfile: data/Dockerfile
    volumes:
      - ./data/build/:/custom_files:rw
      - ./data/valhalla.json:/custom_files/valhalla.json:rw
    environment:
      - serve_tiles=False
      - tileset_name=tiles
      - build_elevation=True
      - build_admins=True
      - build_time_zones=True
      - build_transit=False
      - build_tar=True
      - force_rebuild=True
      - update_existing_config=False
      - use_default_speeds_config=True
      - traffic_name=traffic

  valhalla-run:
    image: opentimes:latest
    container_name: valhalla-build
    user: ${USER_ID}:${GROUP_ID}
    build:
      context: .
      dockerfile: data/Dockerfile
    ports:
      - 8002:8002
    volumes:
      - ./data/build/:/custom_files:rw
      - ./data/valhalla.json:/custom_files/valhalla.json:rw
      - ./data/valhalla.json:/data/valhalla.json:rw
      - ./data/output:/data/output:rw
      # Read only volumes to serve data to the container
      - $HOME/.aws/credentials:/home/valhalla/.aws/credentials:ro
      - ./data/src:/data/src:ro
      - ./data/input:/data/input:ro
      - ./data/intermediate:/data/intermediate:ro
      - ./data/params.yaml:/data/params.yaml:ro
    environment:
      - GIT_COMMIT_SHA
      - use_tiles_ignore_pbf=True
      - update_existing_config=False
      - force_rebuild=False
      - tileset_name=tiles
      - traffic_name=traffic
