---

services:
  # https://github.com/nilsnolde/docker-valhalla/blob/master/docker-compose.yml
  valhalla-build:
    image: ghcr.io/gis-ops/docker-valhalla/valhalla:latest
    container_name: valhalla-build
    user: "${USER_ID}:${GROUP_ID}"
    build:
      context: .
      dockerfile: data/Dockerfile
      args:
        - VALHALLA_UID=${USER_ID}
        - VALHALLA_GID=${GROUP_ID}
    volumes:
      - ./data/build/:/custom_files
    environment:
      - server_threads=32
      - serve_tiles=False
      - tileset_name=tiles
      - build_elevation=True
      - build_admins=True
      - build_time_zones=True
      - build_transit=False
      - build_tar=True
      - force_rebuild=True
      - update_existing_config=True
      - traffic_name=""

  valhalla-run:
    image: ghcr.io/gis-ops/docker-valhalla/valhalla:latest
    container_name: valhalla-build
    user: "${USER_ID}:${GROUP_ID}"
    build:
      context: .
      dockerfile: data/Dockerfile
      args:
        - VALHALLA_UID=${USER_ID}
        - VALHALLA_GID=${GROUP_ID}
    ports:
      - 8002:8002
    volumes:
      - ./data/build/:/custom_files
    environment:
      - server_threads=32
      - serve_tiles=True
      - tileset_name=tiles
