---

stages:
  fetch_tiger_national_file:
    deps:
      - ./src/fetch_tiger.py
    matrix:
      year: ${data.years}
      geography: ${data.geographies.national}
    cmd: >-
      python ./src/fetch_tiger.py --year ${item.year} --geography ${item.geography}
    outs:
      - ./input/tiger/year=${item.year}/geography=${item.geography}/${item.geography}.zip

  fetch_tiger_by_state:
    deps:
      - ./src/fetch_tiger.py
    matrix:
      year: ${data.years}
      geography: ${data.geographies.by_state}
      state: ${data.states}
    cmd: >-
      python ./src/fetch_tiger.py --year ${item.year} --geography ${item.geography} --state ${item.state}
    outs:
      - ./input/tiger/year=${item.year}/geography=${item.geography}/state=${item.state}/${item.state}.zip

  fetch_blockpop_by_state:
    deps:
      - ./src/fetch_blockpop.py
    matrix:
      year: ${data.years}
      state: ${data.states}
    cmd: >-
      python ./src/fetch_blockpop.py --year ${item.year} --state ${item.state}
    outs:
      - ./input/blockpop/year=${item.year}/state=${item.state}/${item.state}.parquet
