---

stages:
  fetch_tiger_national_file:
    deps:
      - ./src/fetch_tiger.py
    matrix:
      year:
        - 2020
      geography:
        - state
        - county
        - zcta
    cmd: >-
      python ./src/fetch_tiger.py --year ${item.year} --geography ${item.geography}
    outs:
      - ./input/tiger/year=${item.year}/geography=${item.geography}/${item.geography}.zip

  fetch_tiger_by_state:
    deps:
      - ./src/fetch_tiger.py
    matrix:
      year:
        - 2020
      geography:
        - county_subdivision
        - place
        - puma
        - tract
        - block_group
        - block
      state:
        - 17
        - 31
    cmd: >-
      python ./src/fetch_tiger.py --year ${item.year} --geography ${item.geography} --state ${item.state}
    outs:
      - ./input/tiger/year=${item.year}/geography=${item.geography}/state=${item.state}/${item.state}.zip
