baseURL = "https://opentimes.org/"
languageCode = "en-us"
title = "OpenTimes"
disableKinds = ["taxonomy", "term"]
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

[markup.goldmark.extensions]
  linkify = false

[params]
  description = "Free multi-modal travel times between U.S. Census geographies"
  author = "Dan Snow"
