---

name: Fetch network data
description: Fetch/cache network.dat and network_settings.json files from DVC
inputs:
  year:
    description: Census year of the network data to fetch
    required: true
  state:
    description: Census state code of the network data to fetch
    required: true

runs:
  using: composite
  steps:
    # Assumes actions/checkout and setup-cloudflare-s3 have already been run
    - name: Cache restore network input data
      id: cache-restore-network-input
      uses: actions/cache/restore@v4
      with:
        path: ./data/intermediate/network
        key: network-${{ inputs.year }}-${{ inputs.state }}-${{ hashFiles('./data/dvc.lock') }}

    - name: Install DVC
      if: steps.cache-restore-network-input.outputs.cache-hit != 'true'
      uses: ./.github/actions/setup-dvc

    - name: Pull DVC objects
      if: steps.cache-restore-network-input.outputs.cache-hit != 'true'
      shell: bash
      working-directory: 'data'
      run: |
        net_path=year=${{ inputs.year }}/geography=state/state=${{ inputs.state }}
        dvc pull --no-run-cache \
          ./intermediate/network/"$net_path"/network.dat \
          ./intermediate/network/"$net_path"/network_settings.json

    - name: Cache save network input data
      if: steps.cache-restore-network-input.outputs.cache-hit != 'true'
      id: cache-save-network-input
      uses: actions/cache/save@v4
      with:
        path: ./data/intermediate/network
        key: network-${{ inputs.year }}-${{ inputs.state }}-${{ hashFiles('./data/dvc.lock') }}
