---

name: Install DVC
description: Installs Python and DVC with S3 support

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python 3.12
      id: setup_python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install DVC
      id: install_python_deps
      shell: bash
      run: pip install dvc[s3]
