---

name: Install DVC
description: Installs Python and DVC with S3 support

runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-suffix: "dvc"

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version-file: .python-version

    - name: Install DVC
      id: install_python_deps
      shell: bash
      run: uv pip install "dvc[s3]"
      env:
        UV_SYSTEM_PYTHON: 1
