---

name: Setup time calculation dependencies
description: Downloads system dependencies for calculating travel times

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Linux dependencies
      id: install_linux_deps
      shell: bash
      run: |
        sudo apt-get install -y libudunits2-dev=2.2.28-3 \
            proj-bin=8.2.1-1 gdal-bin=3.4.1+dfsg-1build4 \
            libgeos-dev=3.10.2-1 libgit2-1.1=1.1.0+dfsg.1-4.1build1

    - name: Setup Python 3.12
      id: setup_python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install Python dependencies
      id: install_python_deps
      shell: bash
      run: pip install .[data]

    - name: Setup R
      id: setup_r
      # Pinned to commit with working-directory support
      uses: r-lib/actions/setup-r@607b3ffaee2e0e54cacd36fab06ada0a120c8c0c
      with:
        r-version: 'renv'
        working-directory: 'data'
        use-public-rspm: true

    - name: Setup R dependencies
      id: setup_r_deps
      uses: r-lib/actions/setup-renv@v2
      with:
        working-directory: 'data'

    - name: Setup Java 21
      id: setup_java
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
