---

name: Increase swap and drive space
description: Increase linux swap and drive space to prevent OoM
inputs:
  swap_override:
    description: Swap file size in bytes, otherwise 90% of remaining space
    required: false

runs:
  using: composite
  steps:
    - name: Report disk space before modification
      shell: bash
      run: df -h

    - name: Remove pre-installed runner software
      shell: bash
      run: |
        # From: https://github.com/AdityaGarg8/remove-unwanted-software/blob/master/action.yml
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/local/.ghcup
        sudo apt-get remove -y '^aspnetcore-.*' '^dotnet-.*' '^llvm-.*' 'php.*' \
          '^mongodb-.*' '^mysql-.*' '^azure-.*' '^google-.*' '^firefox.*' \
          --fix-missing > /dev/null || true
        sudo apt-get autoremove -y > /dev/null
        sudo apt-get clean > /dev/null

    - name: Report disk space after modification
      shell: bash
      run: df -h

    - name: Increase swapfile
      shell: bash
      run: |
        space_left=$(df /dev/root -B 1 --output=avail | grep -v Avail)
        space_mult=0.9
        space_alloc=$(echo "${space_left}*${space_mult}" | bc)
        space_alloc_rnd=$(printf %.0f $(echo ${space_alloc}))
        if [ -n "${{ inputs.swap_override }}" ]; then
          space_alloc_rnd=${{ inputs.swap_override }}
        fi
        echo "Creating swapfile of ${space_alloc_rnd} bytes"
        sudo swapoff -a
        sudo fallocate -l ${space_alloc_rnd} /swapfile
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile
        sudo swapon --show
