---

name: Setup Cloudflare S3
description: Write Cloudflare credentials from GitHub secrets to file
inputs:
  CLOUDFLARE_S3_API_ACCESS_KEY_ID:
    description: A Cloudflare R2 access key ID
    required: true
  CLOUDFLARE_S3_API_SECRET_ACCESS_KEY:
    description: A Cloudflare R2 secret access key
    required: true

runs:
  using: composite
  steps:
    - name: Mask secrets in logs
      shell: bash
      run: |
        echo "::add-mask::${{ inputs.CLOUDFLARE_S3_API_ACCESS_KEY_ID }}"
        echo "::add-mask::${{ inputs.CLOUDFLARE_S3_API_SECRET_ACCESS_KEY }}"

    - name: Setup Cloudflare credentials
      shell: bash
      run: |
        mkdir -p ~/.aws
        echo "[cloudflare]" > ~/.aws/credentials
        echo "aws_access_key_id=${{ inputs.CLOUDFLARE_S3_API_ACCESS_KEY_ID }}" >> ~/.aws/credentials
        echo "aws_secret_access_key=${{ inputs.CLOUDFLARE_S3_API_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
        echo "[default]" > ~/.aws/config
        echo "region = us-east-1" >> ~/.aws/config
        echo "output = json" >> ~/.aws/config
