---

name: calculate-times

on:
  workflow_dispatch:
    inputs:
      # Input values match those in params.yaml
      mode:
        required: true
        description: Travel mode
        default: 'car'
        type: choice
        options:
          - car
          - bicycle
          - transit
          - walk

      year:
        required: true
        description: Census data year
        default: '2020'
        type: choice
        options:
          - '2020'
          - '2021'
          - '2022'
          - '2023'
          - '2024'

      geography:
        required: true
        description: Census data geography
        default: county
        type: choice
        options:
          - state
          - county
          - county_subdivision
          - tract
          - block_group
          - zcta

      state:
        required: true
        description: State to generate times for
        default: '01'
        type: choice
        options:
          - '01'
          - '02'
          - '04'
          - '05'
          - '06'
          - '08'
          - '09'
          - '10'
          - '11'
          - '12'
          - '13'
          - '15'
          - '16'
          - '17'
          - '18'
          - '19'
          - '20'
          - '21'
          - '22'
          - '23'
          - '24'
          - '25'
          - '26'
          - '27'
          - '28'
          - '29'
          - '30'
          - '31'
          - '32'
          - '33'
          - '34'
          - '35'
          - '36'
          - '37'
          - '38'
          - '39'
          - '40'
          - '41'
          - '42'
          - '44'
          - '45'
          - '46'
          - '47'
          - '48'
          - '49'
          - '50'
          - '51'
          - '53'
          - '54'
          - '55'
          - '56'

      centroid_type:
        required: true
        description: Weighted or unweighted
        default: weighted
        type: choice
        options:
          - weighted
          - unweighted

jobs:
  setup-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup time calculation dependencies
        uses: ./.github/actions/setup-time-calculation-dependencies

      - name: Setup Cloudflare credentials
        uses: ./.github/actions/setup-cloudflare-s3
        with:
          CLOUDFLARE_S3_API_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_S3_API_ACCESS_KEY_ID }}
          CLOUDFLARE_S3_API_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_S3_API_SECRET_ACCESS_KEY }}

      - name: Pull DVC objects
        shell: bash
        working-directory: 'data'
        run: |
          dvc pull \
          calculate_times@${{ inputs.mode }}-${{ inputs.year }}-${{ inputs.geography }}-${{ inputs.state }}-${{ inputs.centroid_type }}

# Run setup
#   - Cache all deps
#   - Cloudflare auth
#   - DVC pull
#   - Load origins file
#   - Create splits with script
#   - Send splits to GITHUB_OUTPUT
# Run job matrix
#   - Setup deps for each job
#   - Cloudflare auth
#   - DVC pull
#   - Push output to CF
