---

name: calculate-times

on:
  workflow_dispatch:
    inputs:
      # Input values match those in params.yaml
      mode:
        required: true
        description: Travel mode
        default: 'car'
        type: choice
        options:
          - car
          - bicycle
          - transit
          - walk

      year:
        required: true
        description: Census data year
        default: '2020'
        type: choice
        options:
          - '2020'
          - '2021'
          - '2022'
          - '2023'
          - '2024'

      geography:
        required: true
        description: Census data geography
        default: county
        type: choice
        options:
          - state
          - county
          - county_subdivision
          - tract
          - block_group
          - zcta

      state:
        required: true
        description: State to generate times for
        default: '01'
        type: choice
        options:
          - '01'
          - '02'
          - '04'
          - '05'
          - '06'
          - '08'
          - '09'
          - '10'
          - '11'
          - '12'
          - '13'
          - '15'
          - '16'
          - '17'
          - '18'
          - '19'
          - '20'
          - '21'
          - '22'
          - '23'
          - '24'
          - '25'
          - '26'
          - '27'
          - '28'
          - '29'
          - '30'
          - '31'
          - '32'
          - '33'
          - '34'
          - '35'
          - '36'
          - '37'
          - '38'
          - '39'
          - '40'
          - '41'
          - '42'
          - '44'
          - '45'
          - '46'
          - '47'
          - '48'
          - '49'
          - '50'
          - '51'
          - '53'
          - '54'
          - '55'
          - '56'

      centroid_type:
        required: true
        description: Weighted or unweighted
        default: weighted
        type: choice
        options:
          - weighted
          - unweighted

jobs:
  setup-jobs:
    runs-on: ubuntu-latest

    outputs:
      chunks: ${{ steps.create-job-chunks.outputs.chunks }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup time calculation dependencies
        uses: ./.github/actions/setup-time-calculation-dependencies

      - name: Setup Cloudflare credentials
        uses: ./.github/actions/setup-cloudflare-s3
        with:
          CLOUDFLARE_S3_API_ACCESS_KEY_ID: |
            ${{ secrets.CLOUDFLARE_S3_API_ACCESS_KEY_ID }}
          CLOUDFLARE_S3_API_SECRET_ACCESS_KEY: |
            ${{ secrets.CLOUDFLARE_S3_API_SECRET_ACCESS_KEY }}

      - name: Pull DVC objects
        shell: bash
        working-directory: 'data'
        run: |
          od_path=year=${{ inputs.year }}/geography=${{ inputs.geography }}/state=${{ inputs.state }}/${{ inputs.state }}.parquet
          dvc pull --no-run-cache ./intermediate/cenloc/"$od_path"

      - name: Create job chunks
        id: create-job-chunks
        shell: bash
        working-directory: 'data'
        run: "python ./src/split_origin.py
          --year ${{ inputs.year }} --geography ${{ inputs.geography }}
          --state ${{ inputs.state }} >> $GITHUB_OUTPUT"

  run-jobs:
    runs-on: ubuntu-latest
    needs: setup-jobs
    strategy:
      matrix:
        chunk: ${{ fromJSON(needs.setup-jobs.outputs.chunks) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup time calculation dependencies
        uses: ./.github/actions/setup-time-calculation-dependencies

      - name: Setup Cloudflare credentials
        uses: ./.github/actions/setup-cloudflare-s3
        with:
          CLOUDFLARE_S3_API_ACCESS_KEY_ID: |
            ${{ secrets.CLOUDFLARE_S3_API_ACCESS_KEY_ID }}
          CLOUDFLARE_S3_API_SECRET_ACCESS_KEY: |
            ${{ secrets.CLOUDFLARE_S3_API_SECRET_ACCESS_KEY }}

      - name: Pull DVC objects
        shell: bash
        working-directory: 'data'
        run: |
          od_path=year=${{ inputs.year }}/geography=${{ inputs.geography }}/state=${{ inputs.state }}/${{ inputs.state }}.parquet
          dvc pull --no-run-cache \
            ./intermediate/cenloc/"$od_path" \
            ./intermediate/destpoint/"$od_path" \
            ./intermediate/network/year=${{ inputs.year }}/geography=state/state=${{ inputs.state }}/network.dat \
            ./intermediate/network/year=${{ inputs.year }}/geography=state/state=${{ inputs.state }}/network_settings.json

      - name: Run job chunk
        shell: bash
        working-directory: 'data'
        run: "Rscript src/calculate_times.R
          --mode ${{ inputs.mode }} --year ${{ inputs.year }}
          --geography ${{ inputs.geography }} --state ${{ inputs.state }}
          --centroid_type ${{ inputs.centroid_type }}
          --chunk ${{ matrix.chunk }}
          "
