---

name: create-osrm-networks
run-name: create-osrm-networks-${{ inputs.year }}

on:
  workflow_dispatch:
    inputs:
      year:
        required: true
        description: OSM data year
        default: '2020'
        type: choice
        options:
          - '2020'
          - '2021'
          - '2022'
          - '2023'
          - '2024'

      override_modes:
        required: false
        description: |
          Comma-separated list of OSRM modes to run e.g. car,foot.
          Will run all if null
        type: string

      override_states:
        required: false
        description: |
          Comma-separated state codes to run e.g. 01,06.
          Will run all if null
        type: string

env:
  AWS_DEFAULT_REGION: us-east-1
  # See: https://github.com/aws/aws-cli/issues/5262#issuecomment-705832151
  AWS_EC2_METADATA_DISABLED: true
  PYTHONUNBUFFERED: "1"

jobs:
  setup-jobs:
    runs-on: ubuntu-24.04

    outputs:
      modes: ${{ steps.create-mode-jobs.outputs.param }}
      states: ${{ steps.create-state-jobs.outputs.param }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create mode jobs
        id: create-mode-jobs
        uses: ./.github/actions/parse-gh-input
        with:
          param_path: '.times.mode'
          param_override: '${{ inputs.override_modes }}'

      - name: Create state jobs
        id: create-state-jobs
        uses: ./.github/actions/parse-gh-input
        with:
          param_path: '.input.state'
          param_override: '${{ inputs.override_states }}'

  run-job:
    runs-on: ubuntu-24.04
    needs: setup-jobs
    strategy:
      # Don't fail all chunks if one fails
      fail-fast: false
      matrix:
        mode: ${{ fromJSON(needs.setup-jobs.outputs.modes) }}
        state: ${{ fromJSON(needs.setup-jobs.outputs.states) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Cloudflare credentials
        uses: ./.github/actions/setup-cloudflare-s3
        with:
          CLOUDFLARE_S3_API_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_S3_API_ACCESS_KEY_ID }}
          CLOUDFLARE_S3_API_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_S3_API_SECRET_ACCESS_KEY }}

      - name: Install DVC
        uses: ./.github/actions/setup-dvc

      - name: Pull DVC objects
        shell: bash
        working-directory: 'data'
        run: |
          uv run dvc pull --no-run-cache \
            ./intermediate/osmextract/year=${{ inputs.year }}/geography=state/state=${{ matrix.state }}/${{ matrix.state }}.osm.pbf

      - name: Run job chunk
        shell: bash
        working-directory: 'data'
        run: |
          uv run dvc repro -s create_osrmnetwork_by_state@${{ matrix.mode }}-${{ inputs.year }}-${{ matrix.state }}

      - name: Write network files to S3
        shell: bash
        working-directory: 'data'
        run: |
          export AWS_MAX_ATTEMPTS=5
          ls -lah ./intermediate/osrmnetwork/mode=${{ matrix.mode }}/year=${{ inputs.year }}/geography=state/state=${{ matrix.state }}/osrmnetwork.tar.zst
          aws s3 cp --endpoint-url \
            https://${{ vars.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com \
             ./intermediate/osrmnetwork/mode=${{ matrix.mode }}/year=${{ inputs.year }}/geography=state/state=${{ matrix.state }}/osrmnetwork.tar.zst \
             s3://opentimes-resources/osrmnetwork/mode=${{ matrix.mode }}/year=${{ inputs.year }}/geography=state/state=${{ matrix.state }}/osrmnetwork.tar.zst \
            --profile cloudflare
