name: lychee

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check links
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: |
            --base . --verbose
            --no-progress --accept '100..=103,200..=299,403'
            './site/content/**/*.md'
          fail: true
