on:
  workflow_dispatch:
  release:
    types: [published]

name: pypi-publish

env:
  PYTHONUNBUFFERED: "1"
  UV_SYSTEM_PYTHON: 1

jobs:
  pypi-publish:
    name: pypi-publish
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/opentimes
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install Python dependencies
        run: uv pip install .

      - name: Build Python dist
        run: uv build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
